### ISSUE TITLE
Binder example does not work

### ISSUE THREAD

**Issue by 1kastner** [deathbeds/nbconvert-pdfqt#2]
When I clicked on the binder link at https://mybinder.org/v2/gh/deathbeds/nbconvert-pdfqt/master?urlpath=lab%2Ftree%2Fnotebooks%2Findex.ipynb and tried to run the Jupyter Notebook, the following popped up:

```
[NbConvertApp] Converting notebook Examples.ipynb to pdfqt
[NbConvertApp] Building PDF...
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/srv/conda/envs/notebook/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/src/nbconvert_pdfqt/printer.py", line 7, in <module>
    from PyQt5 import QtCore, QtWidgets, QtWebEngineWidgets, QtGui, QtWebChannel
ImportError: libpci.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/jovyan/src/nbconvert_pdfqt/exporter.py", line 45, in from_notebook_node
    QTWEBENGINE_CHROMIUM_FLAGS="--headless --disable-gpu --no-sandbox --single-process --enable-logging --log-level=0"
  File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/srv/conda/envs/notebook/bin/python', '-m', 'nbconvert_pdfqt.printer', '/tmp/tmpez1jn597']' returned non-zero exit status 1.

```

**Comment by bollwyvl** [comment]
Yeah, sorry for the inconvenience, turns out docker isn't all that
reproducible over a couple years, if you just randomly install stuff and
don't lock anything down.

Most likely the issue is:
- qt dependency drift (for which there is an open issue)
- network perms (once you fight past that, it complains about not getting
ports to start its internal server)

May try to fix but it might be a while, as I have no immediate need for it:
PRs welcome!
